version: "3.6"
services:
  workspace:
    build:
      context: ./docker/workspace
      args:
        - USERID=${USERID}
        - GROUPID=${GROUPID}
        - USER_NAME=${USER_NAME}
        - GROUP_NAME=${GROUP_NAME}
    tty: true
    hostname: workspace
    volumes:
      - ./projects/chat:/projects/chat
      - ./projects/congregate:/projects/congregate
      - ./projects/realtime:/projects/realtime
    networks:
      - webnetwork
  redisdb:
    build:
      context: ./docker/redis
    volumes:
      - ./docker/redis/data:/data
    networks:
      - webnetwork
    hostname: redisdb
  nginx:
     build:
       context: ./docker/nginx
       args:
        - USERID=${USERID}
        - GROUPID=${GROUPID}
        - USER_NAME=${USER_NAME}
        - GROUP_NAME=${GROUP_NAME}
     restart: always
     ports:
       - ${HTTP_PORT}:80
       - ${HTTPS_PORT}:443
     volumes:
        - ./projects/congregate:/backend/congregate
        - ./projects/placeholder:/backend/placeholder
        - ./wordpress:/backend/wordpress
        - ./devtools/adminer:/backend/devtools/adminer
        - ./docker/nginx/sites:/etc/nginx/conf.d
     depends_on:
        - phpfpm
        - redisdb
        - db
        - nodejs
     networks:
        webnetwork:
            aliases:
                - realtime.test
     hostname: nginx

  meilisearch:
    image: 'getmeili/meilisearch:latest'
    environment:
       - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-meilimaster123}
       - MEILI_ENV=${MEILI_ENV:-production}
    volumes:
     - ./docker/meilisearch/data:/data.ms
    networks:
      - webnetwork
    ports:
     - ${MEILI_PORT:-7700}:7700
    hostname: meilisearch

  db:
    build:
      context: ./docker/db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-dbpassword}
      - MYSQL_USER=${MYSQL_USER:-dbuser}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-dbuser}
    networks:
      - webnetwork
    volumes:
     - ./docker/db/data:/var/lib/mysql
     - ./projects/congregate:/congregate
    hostname: mariadb

  postgres:
    build:
       context: ./docker/postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-dbpassword}
      - POSTGRES_USER=${POSTGRES_USER:-dbuser}
    networks:
      - webnetwork
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    hostname: postgres

  phpfpm:
    build:
      context: ./docker/phpfpm
      args:
        - USERID=${USERID}
        - GROUPID=${GROUPID}
        - USER_NAME=${USER_NAME}
        - GROUP_NAME=${GROUP_NAME}
    volumes:
      - ./projects/congregate:/backend/congregate
      - ./projects/placeholder:/backend/placeholder
      - ./wordpress:/backend/wordpress
      - ./devtools/adminer:/backend/devtools/adminer
    networks:
      - webnetwork
    hostname: phpfpm

  cron:
    build:
      context: ./docker/cron
    volumes:
      - ./projects/congregate:/backend/congregate
    networks:
      - webnetwork
    hostname: cron


  supervisor:
    build:
      context: ./docker/supervisor
    volumes:
      - ./projects/congregate:/backend/congregate
    networks:
      - webnetwork
    hostname: supervisor

  nodejs:
    build:
      context: ./docker/nodejs
    volumes:
      - ./projects/realtime:/projects/realtime
      - ./projects/chat:/projects/chat
      - ./projects/congregate:/projects/congregate
      - ./projects/placeholder:/projects/placeholder
    hostname: nodejs
    command: tail -F anything
    ports:
      - ${NODE_PORT}:8080
      - ${CP_REALTIME_PORT}:3000
      - ${CP_CONGREGATE_PORT}:4000
    networks:
      - webnetwork

  mongo:
    build:
       context: ./docker/mongo
    restart: always
    environment:
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD:-dbpassword}
      - MONGODB_USERNAME=${MONGODB_USERNAME:-dbuser}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD:-dbpassword}
    volumes:
      - ./docker/mongo/data:/data/db
    networks:
      - webnetwork
    hostname: mongodb
    # ports:
    #  - 27017:27017
    #  - 27018:27018

  mail:
    image: mailhog/mailhog
    ports:
      - ${MAILHOG_PORT:-1025}:1025
      - ${MAILHOG_UI:-8025}:8025
    networks:
      - webnetwork
    hostname: mailhog

  minio:
    build:
      context: './docker/minio'
    volumes:
      - ./docker/minio/data:/data
    ports:
      - ${MINIO_PORT}:9000
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-minio}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-minio123}
    networks:
      - webnetwork
    hostname: minio
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  webnetwork:
    name: ${NETWORK_NAME:-congregate_dev}
    driver: bridge
